name: build
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install flake8
      run: pip install flake8 flake8-import-order flake8-future-import flake8-commas flake8-logging-format
    - name: Lint with flake8
      run: |
        flake8 --version
        flake8
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies and mypy
      run: |
        pip install -r requirements.txt
        pip install mypy django-stubs types-urllib3
    - name: Verify mypy types
      run: |
        mypy --version
        mypy discord_integration
